version: "3.9"

services:
  app:
    image: backend-academy:lab1
    ports:
      - "8080:8080"

  mockserver:
    image: mockserver/mockserver:5.14.0
    command: -serverPort 1080
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /initializerJson.json
    volumes:
      - "./mocks/mockserver/initializerJson.json:/initializerJson.json"

#  graphql-mock:
#    build: ./mocks/graphql/
#    ports:
#      - "4444:4444"
